stages:  
  generate_cot:
    cmd: >
      python -m src.generate_cot
      --train_path ${data.raw_source}
      --output_path ${data.raw_working}
    deps:
      - ${data.raw_source}
      - src/solvers
      - src/generate_cot.py
    outs:
      - ${data.raw_working}


  prepare_data:
    cmd: >
      python -m src.prepare_dataset
      --data_path ${data.raw_working}
      --output_path ${data.train_generated}
      --seed ${train.seed}
      --tokenizer_path ${model.id}
    deps:
      - ${data.raw_working}
      - src/prepare_dataset.py
    params:
      - train.seed
      - model.id
    outs:
      - ${data.train_generated}


  base_sft_train:
    cmd: >
      python -m src.sft_train 
      --wandb_run_basename ${wandb.wandb_base_run_name}_base_sft_train
      --model_id ${model.id}
      --data ${data.dataset_name}
      --train_path ${data.train_generated}
      --seed ${train.seed}
      --save_steps ${train.eval_steps}
      --output_dir ${model.sft_output_dir}
      --batch_size ${train.batch_size}
      --grad_accum ${train.grad_accum}
      --epochs ${train.epochs}
      --max_hours ${train.max_hours}
      --lr ${train.lr}
      --lora_r ${train.lora_r}
      --lora_alpha ${train.lora_alpha}
      --max_seq_len ${train.max_seq_len}
      --train_telemetry
      --loss_impl cce
      --cce_impl cce
      --cce_compare_default_loss_once
    deps:
      - ${data.train_generated}
      - src/sft_train.py
    params:
      - wandb.wandb_base_run_name
      - model.id
      - data.dataset_name
      - train.max_hours
      - train.batch_size
      - train.grad_accum
      - train.epochs
      - train.eval_steps
      - train.seed
      - train.lr
      - train.lora_r
      - train.lora_alpha
      - train.max_seq_len
    outs:
      - ${model.sft_output_dir}:
          persist: true