data:
  raw_source: /kaggle/input/nvidia-nemotron-3-reasoning-challenge/train.csv
  raw_working: data/solved/train-cot.csv
  train_prepared: data/prepared/train_stratified.csv
  train_generated: data/generated/train_with_syntetic.csv
  val_prepared: data/prepared/val_stratified.csv
  dataset_name: algorithmic_cot
model:
  id: /kaggle/input/models/metric/nemotron-3-nano-30b-a3b-bf16/transformers/default/1
  sft_output_dir: models/sft_v0.0.7
split:
  val_size: 0.1
train:
  lr: 2e-4
  batch_size: 4
  grad_accum: 8
  epochs: 4
  seed: 31231
  eval_steps: 205
  max_hours: 10.0
evaluate:
  scores_file: data/scores/validation_scores.json
wandb:
  wandb_base_run_name: sft_v0.0.7
